#!/usr/bin/env bash
set -euo pipefail

# utm-bundle.sh — Build a ready-to-go USB drive for Dell provisioning
#
# Copies scripts, generates SETUP.bat (with embedded credentials) and
# README.txt onto a USB mount point. Plug in, double-click, walk away.
#
# Usage:
#   utm-bundle.sh /Volumes/PROVISION [--username=mom] [--password=Pass123] [--authkey=tskey-auth-xxx]

# Load shared configuration
source "$(dirname "$0")/utm.conf"

# Load .env if present (for TAILSCALE_AUTHKEY etc.)
ENV_FILE="$(dirname "$0")/.env"
if [[ -f "$ENV_FILE" ]]; then
    set -a
    source "$ENV_FILE"
    set +a
fi

# ── Parse arguments ──────────────────────────────────────────────────
USB_PATH=""
AUTHKEY=""
STD_USERNAME=""
STD_PASSWORD=""

for arg in "$@"; do
    case "$arg" in
        --authkey=*)  AUTHKEY="${arg#--authkey=}" ;;
        --username=*) STD_USERNAME="${arg#--username=}" ;;
        --password=*) STD_PASSWORD="${arg#--password=}" ;;
        --help|-h)
            echo "Usage: utm-bundle.sh <usb-mount-point> [options]"
            echo ""
            echo "  <usb-mount-point>   Path to mounted USB drive (e.g. /Volumes/PROVISION)"
            echo ""
            echo "Options:"
            echo "  --username=NAME     Standard user account name (default: mom)"
            echo "  --password=PASS     Standard user account password"
            echo "  --authkey=KEY       Tailscale auth key (overrides .env)"
            exit 0
            ;;
        -*)
            echo "ERROR: Unknown option: $arg"
            exit 1
            ;;
        *)
            if [[ -z "$USB_PATH" ]]; then
                USB_PATH="$arg"
            else
                echo "ERROR: Unexpected argument: $arg"
                exit 1
            fi
            ;;
    esac
done

# ── Validate inputs ─────────────────────────────────────────────────
if [[ -z "$USB_PATH" ]]; then
    echo "ERROR: USB mount point is required"
    echo "Usage: utm-bundle.sh <usb-mount-point> [options]"
    exit 1
fi

if [[ ! -d "$USB_PATH" ]]; then
    echo "ERROR: $USB_PATH is not a directory"
    exit 1
fi

if [[ ! -w "$USB_PATH" ]]; then
    echo "ERROR: $USB_PATH is not writable"
    exit 1
fi

# Auth key — from flag or .env
if [[ -z "$AUTHKEY" && -n "${TAILSCALE_AUTHKEY:-}" ]]; then
    AUTHKEY="$TAILSCALE_AUTHKEY"
fi
if [[ -z "$AUTHKEY" ]]; then
    echo "ERROR: Tailscale auth key required (set in .env or pass --authkey=)"
    exit 1
fi
if [[ "$AUTHKEY" != tskey-auth-* ]]; then
    echo "ERROR: Auth key must start with tskey-auth-"
    exit 1
fi

# Interactive prompts for missing credentials
if [[ -z "$STD_USERNAME" ]]; then
    read -rp "Standard username [mom]: " STD_USERNAME
    STD_USERNAME="${STD_USERNAME:-mom}"
fi

if [[ -z "$STD_PASSWORD" ]]; then
    while true; do
        read -rsp "Password for $STD_USERNAME: " STD_PASSWORD
        echo
        if [[ -z "$STD_PASSWORD" ]]; then
            echo "ERROR: Password cannot be empty"
            continue
        fi
        read -rsp "Confirm password: " confirm
        echo
        if [[ "$STD_PASSWORD" != "$confirm" ]]; then
            echo "ERROR: Passwords do not match"
            continue
        fi
        break
    done
fi

# Reject dangerous characters
if [[ "$STD_PASSWORD" == *'!'* ]]; then
    echo "ERROR: Password cannot contain '!' (eaten by cmd.exe EnableDelayedExpansion)"
    exit 1
fi
if [[ "$STD_PASSWORD" == *'%'* ]]; then
    echo "ERROR: Password cannot contain '%' (triggers cmd.exe variable expansion)"
    exit 1
fi

echo ""
echo "USB Bundle"
echo "============================================================"
echo "  Target:     $USB_PATH"
echo "  Username:   $STD_USERNAME"
echo "  Auth key:   ${AUTHKEY:0:20}..."
echo "============================================================"
echo ""

# ── Copy scripts ────────────────────────────────────────────────────
echo "Copying scripts..."

# Clean and recreate scripts dir on USB
rm -rf "${USB_PATH:?}/scripts"
mkdir -p "$USB_PATH/scripts/lib"

# Copy .bat and .ps1 files
cp_count=0
for f in "$SCRIPTS_DIR"/*.bat "$SCRIPTS_DIR"/*.ps1; do
    [[ -f "$f" ]] || continue
    cp "$f" "$USB_PATH/scripts/"
    ((cp_count++)) || true
done

for f in "$SCRIPTS_DIR"/lib/*.bat; do
    [[ -f "$f" ]] || continue
    cp "$f" "$USB_PATH/scripts/lib/"
    ((cp_count++)) || true
done

echo "  Copied $cp_count files"

# ── Generate SETUP.bat ──────────────────────────────────────────────
echo "Generating SETUP.bat..."

# Write with LF, then convert to CRLF
cat > "$USB_PATH/SETUP.bat.tmp" << 'SETUPEOF'
@echo off
:: ============================================================================
:: SETUP.bat - Dell Provisioning Launcher
:: ============================================================================
:: Generated by utm-bundle.sh — double-click to provision this computer.
:: ============================================================================

:: ── UAC Elevation ──────────────────────────────────────────────────
net session >nul 2>&1
if errorlevel 1 (
    echo Requesting administrator privileges...
    powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
    exit /b
)

:: ── Network Check ──────────────────────────────────────────────────
echo.
echo Checking network connectivity...
ping -n 1 -w 3000 8.8.8.8 >nul 2>&1
if errorlevel 1 (
    echo.
    echo  *** WARNING: No internet connection detected ***
    echo.
    echo  Please connect to WiFi before continuing.
    echo  Press any key to try again, or Ctrl+C to cancel.
    echo.
    pause >nul
    ping -n 1 -w 3000 8.8.8.8 >nul 2>&1
    if errorlevel 1 (
        echo.
        echo  Still no connection. Continuing anyway...
        echo  Some steps may fail without internet.
        echo.
        timeout /t 5 >nul
    )
)

:: ── Detect USB Path ────────────────────────────────────────────────
set "USB_DIR=%~dp0"
if "%USB_DIR:~-1%"=="\" set "USB_DIR=%USB_DIR:~0,-1%"

SETUPEOF

# Inject credentials (before EnableDelayedExpansion in the master script)
{
    echo ":: ── Credentials (embedded by utm-bundle.sh) ──────────────────"
    echo "set \"TAILSCALE_AUTHKEY=$AUTHKEY\""
    echo "set \"STANDARD_USERNAME=$STD_USERNAME\""
    echo "set \"STANDARD_PASSWORD=$STD_PASSWORD\""
    echo ""
} >> "$USB_PATH/SETUP.bat.tmp"

cat >> "$USB_PATH/SETUP.bat.tmp" << 'SETUPEOF2'
:: ── Copy Scripts to C:\ ────────────────────────────────────────────
echo.
echo Copying provisioning scripts to C:\provision ...
if exist C:\provision\scripts rmdir /s /q C:\provision\scripts
mkdir C:\provision\scripts\lib 2>nul
xcopy "%USB_DIR%\scripts\*.*" "C:\provision\scripts\" /s /e /y /q >nul
if errorlevel 1 (
    echo ERROR: Failed to copy scripts to C:\provision
    pause
    exit /b 1
)

:: ── Run Master Script ──────────────────────────────────────────────
echo.
echo Starting provisioning...
echo ============================================================
echo.
call C:\provision\scripts\00-setup-master.bat --force
set "SETUP_RESULT=%ERRORLEVEL%"

:: ── Copy Logs Back to USB ──────────────────────────────────────────
echo.
echo Copying logs back to USB...
if exist C:\provision\logs (
    mkdir "%USB_DIR%\logs" 2>nul
    xcopy "C:\provision\logs\*.*" "%USB_DIR%\logs\" /s /e /y /q >nul 2>&1
)
if exist C:\provision\output (
    mkdir "%USB_DIR%\output" 2>nul
    xcopy "C:\provision\output\*.*" "%USB_DIR%\output\" /s /e /y /q >nul 2>&1
)

:: ── Result Banner ──────────────────────────────────────────────────
echo.
echo ============================================================
if %SETUP_RESULT% EQU 0 (
    echo  Setup completed successfully!
) else (
    echo  Setup finished with errors [exit code %SETUP_RESULT%]
    echo  Check logs on USB drive for details.
)
echo ============================================================
echo.
echo  Logs saved to: %USB_DIR%\logs
echo  Credentials:   %USB_DIR%\output\credentials.txt
echo.
echo  You can now remove the USB drive and restart the computer.
echo.
pause
exit /b %SETUP_RESULT%
SETUPEOF2

# Convert to CRLF
sed 's/$/\r/' "$USB_PATH/SETUP.bat.tmp" > "$USB_PATH/SETUP.bat"
rm "$USB_PATH/SETUP.bat.tmp"

# ── Generate README.txt ─────────────────────────────────────────────
echo "Generating README.txt..."

sed 's/$/\r/' > "$USB_PATH/README.txt" << 'READMEEOF'
Dell Provisioning USB
=====================

Instructions:

  1. Connect the computer to WiFi
  2. Plug in this USB drive
  3. Open the USB drive in File Explorer
  4. Double-click SETUP.bat
  5. Click YES on the admin prompt
  6. Wait ~20 minutes for setup to complete
  7. Press any key when done
  8. Remove USB drive and restart the computer

What gets installed:

  - Tailscale VPN (remote access)
  - TightVNC (screen sharing)
  - Google Chrome (with ad blocker)
  - iTunes
  - Malwarebytes (security)
  - DNS filtering (malware/phishing protection)
  - Firewall rules and security hardening
  - Standard user account

After setup, connect remotely via Tailscale + VNC.
Check the output/credentials.txt file for VNC password.
READMEEOF

# ── Verify bundle ───────────────────────────────────────────────────
echo ""
echo "Verifying bundle..."

errors=0

for expected in \
    "$USB_PATH/SETUP.bat" \
    "$USB_PATH/README.txt" \
    "$USB_PATH/scripts/00-setup-master.bat" \
    "$USB_PATH/scripts/lib/config.bat" \
    "$USB_PATH/scripts/lib/log.bat" \
    "$USB_PATH/scripts/lib/admin.bat"; do
    if [[ ! -f "$expected" ]]; then
        echo "  MISSING: $expected"
        ((errors++)) || true
    fi
done

# Verify CRLF in SETUP.bat
if ! file "$USB_PATH/SETUP.bat" | grep -q "CRLF"; then
    echo "  WARNING: SETUP.bat may not have CRLF line endings"
    ((errors++)) || true
fi

if (( errors > 0 )); then
    echo ""
    echo "ERROR: Bundle verification failed ($errors issues)"
    exit 1
fi

# Count total files
total=$(find "$USB_PATH/scripts" -type f | wc -l | tr -d ' ')

echo ""
echo "============================================================"
echo "Bundle complete!"
echo "============================================================"
echo ""
echo "  USB:       $USB_PATH"
echo "  Scripts:   $total files"
echo "  Launcher:  SETUP.bat"
echo "  Readme:    README.txt"
echo ""
echo "  Ready to plug into the Dell and double-click SETUP.bat"
echo "============================================================"
